# Generated by Django 6.0.2 on 2026-02-09 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_id_alter_enroll_id_alter_lecture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_file',
            field=models.FileField(blank=True, help_text='Upload an .mp4 (H.264/AAC recommended).', null=True, upload_to='lectures/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
