# Generated by Django 6.0.2 on 2026-02-19 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_enroll_unique_together_lectureprogress_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                UPDATE courses_topic
                SET topic_is_active = CASE
                    WHEN topic_is_active IS NULL THEN 1
                    WHEN LOWER(topic_is_active) IN ('yes', 'y', 'true', '1') THEN 1
                    ELSE 0
                END;
                """,
                """
                UPDATE courses_course
                SET
                    course_is_active = CASE
                        WHEN course_is_active IS NULL THEN 1
                        WHEN LOWER(course_is_active) IN ('yes', 'y', 'true', '1') THEN 1
                        ELSE 0
                    END,
                    course_is_featured = CASE
                        WHEN course_is_featured IS NULL THEN 0
                        WHEN LOWER(course_is_featured) IN ('yes', 'y', 'true', '1') THEN 1
                        ELSE 0
                    END;
                """,
                """
                UPDATE courses_lecture
                SET lecture_previewable = CASE
                    WHEN lecture_previewable IS NULL THEN 1
                    WHEN LOWER(lecture_previewable) IN ('yes', 'y', 'true', '1') THEN 1
                    ELSE 0
                END;
                """,
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(unique=True, verbose_name='Course Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_topic',
            field=models.ManyToManyField(related_name='courses', to='courses.topic', verbose_name='Course Topic'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_previewable',
            field=models.BooleanField(default=True, verbose_name='Is Previewable?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=5),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(max_length=55, unique=True, verbose_name='Topic Slug'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_slug'], name='courses_cou_course__491355_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_created_at'], name='courses_cou_course__308f29_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_is_active', 'course_is_featured'], name='courses_cou_course__ccebc1_idx'),
        ),
        migrations.AddIndex(
            model_name='enroll',
            index=models.Index(fields=['user', 'course'], name='courses_enr_user_id_e2a6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='enroll',
            index=models.Index(fields=['enrolled_date'], name='courses_enr_enrolle_5b2250_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['lecture_slug'], name='courses_lec_lecture_dc97de_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course', 'lecture_slug'], name='courses_lec_course__989cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureprogress',
            index=models.Index(fields=['user', 'completed'], name='courses_lec_user_id_db4357_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureprogress',
            index=models.Index(fields=['lecture', 'completed'], name='courses_lec_lecture_f4c39a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', 'rating'], name='courses_rev_course__b944e5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='courses_rev_created_f66d22_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['topic_slug'], name='courses_top_topic_s_ea6be9_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['topic_is_active'], name='courses_top_topic_i_46980f_idx'),
        ),
    ]
