# Generated by Django 5.1.4 on 2026-02-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_enroll_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_slug',
            field=models.SlugField(blank=True, verbose_name='Lecture Slug'),
        ),
    ]
