# Generated by Django 5.1.4 on 2026-02-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-course_created_at',)},
        ),
    ]
