# Generated by Django 6.0.2 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lecture_lecture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
    ]
