# Generated by Django 6.0.2 on 2026-02-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lecture_lecture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('course', 'lecture_slug'), name='uniq_lecture_slug_per_course'),
        ),
    ]
